//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookings.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Staff
    {
       
        public int StaffID { get; set; }
        public int CompanyID { get; set; }
        public int StaffRoleID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }

        [DisplayName("User Name")]
        [Required(ErrorMessage ="This Field is required")]
        public string Username { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This Field is required")]
        public string Password { get; set; }
        public bool Active { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
